--Lab 2.4
--Завдання 1

--1.1
CREATE VIEW CERTIVICATE_MILITARY (ID,NAME,ISSUE_DATE,ADDRESSEE,LOCATION,PERSONFK,TEXT)
AS SELECT C.CERTIFICATEPK, C.NAME, C.ISSUE_DATE,C.ADDRESSEE,C.LOCATION,C.PERSONFK,C.TEXT
   FROM CERTIFICATE C
   WHERE C.NAME = 'Воєнний білет';
   
SELECT * FROM CERTIVICATE_MILITARY CM WHERE CM.ISSUE_DATE<>TO_DATE('31.10.2021','DD.MM.YYYY');

SELECT MIN(CM.ISSUE_DATE), MAX(CM.ISSUE_DATE) 
FROM CERTIVICATE_MILITARY CM
WHERE CM.LOCATION = 'Сапанів';

SELECT DISTINCT P.PERSONPK,P.NAME
FROM CERTIVICATE_MILITARY CM inner join PERSON P
     on CM.PERSONFK = P.PERSONPK INNER JOIN CERTIFICATE C
     on CM.PERSONFK = C.PERSONFK
WHERE CM.ID != C.CERTIFICATEPK
ORDER BY 1;

SELECT LOCATION, COUNT(*)
FROM CERTIVICATE_MILITARY CM
GROUP BY LOCATION;

DROP VIEW CERTIVICATE_MILITARY;

--1.2

CREATE VIEW SERTIFICATE_2(ID,NAME,ISSUE_DATE,ADDRESSEE,LOCATION,PERSONFK)
as SELECT C.CERTIFICATEPK, C.NAME, C.ISSUE_DATE,C.ADDRESSEE,C.LOCATION,C.PERSONFK
   FROM CERTIFICATE C
   GROUP BY C.CERTIFICATEPK, C.NAME, C.ISSUE_DATE,C.ADDRESSEE,C.LOCATION,C.PERSONFK
   HAVING(SELECT COUNT(C1.PERSONFK)
          FROM CERTIFICATE C1
          WHERE C1.PERSONFK =C.PERSONFK
          GROUP BY C1.PERSONFK)>1
   ORDER BY C.PERSONFK;
          
SELECT * FROM SERTIFICATE_2 С2 WHERE LOCATION IN ('Київ','Сапанів');

SELECT *
FROM SERTIFICATE_2 C
GROUP BY C.ID, C.NAME, C.ISSUE_DATE,C.ADDRESSEE,C.LOCATION,C.PERSONFK
HAVING (SELECT COUNT(C1.PERSONFK)
        FROM SERTIFICATE_2 C1
        WHERE C1.PERSONFK = C.PERSONFK
        GROUP BY C1.PERSONFK)>2
ORDER BY C.PERSONFK;

SELECT S2.LOCATION,P.NAME,COUNT(S2.PERSONFK)
FROM SERTIFICATE_2 S2 INNER JOIN PERSON P ON S2.PERSONFK = P.PERSONPK
GROUP BY S2.LOCATION, P.NAME;

SELECT LOCATION || ' видав', COUNT(LOCATION), NAME 
FROM SERTIFICATE_2 S2
GROUP BY NAME, LOCATION
ORDER BY LOCATION;

DROP VIEW SERTIFICATE_2;

--1.3

CREATE VIEW PERSON_KUIV (ID,NAME,PHONE)
as  SELECT DISTINCT P.PERSONPK, P.NAME, P.PHONE 
    FROM PERSON P INNER JOIN CERTIFICATE C on P.PERSONPK = C.PERSONFK
    WHERE C.LOCATION = 'Київ'
    ORDER BY P.PERSONPK;

SELECT * FROM PERSON_KUIV WHERE ID > 13;

SELECT COUNT(*)
FROM PERSON_KUIV;

SELECT DISTINCT P.NAME,COUNT(*),C.LOCATION
FROM PERSON P INNER JOIN CERTIFICATE C 
     ON P.PERSONPK = C.PERSONFK INNER JOIN PERSON_KUIV PK
     ON P.PERSONPK = PK.ID
WHERE C.LOCATION != 'Київ'
GROUP BY P.NAME,C.LOCATION;

SELECT P.NAME
FROM PERSON P INNER JOIN CERTIFICATE C 
     ON P.PERSONPK = C.PERSONFK INNER JOIN PERSON_KUIV PK
     ON P.PERSONPK = PK.ID
WHERE C.LOCATION = 'Сапанів';

DROP VIEW PERSON_KUIV;

--Завдання 2
--2.1

CREATE VIEW COUNT_PERSON(COUNT_P)
as SELECT COUNT(*) FROM PERSON;

SELECT * From COUNT_PERSON;

DROP VIEW COUNT_PERSON;

--2.2

CREATE VIEW COUNT_CERTIFICATE_BY_LOCATION(BY_KUIV,BY_SAPANIV,BY_HARKIV,BY_LVIV,BY_KREMENETS)
as SELECT Distinct(SELECT COUNT(*)FROM CERTIFICATE WHERE LOCATION = 'Київ'),
          (SELECT COUNT(*)FROM CERTIFICATE WHERE LOCATION = 'Сапанів'),
          (SELECT COUNT(*)FROM CERTIFICATE WHERE LOCATION = 'Харків'),
          (SELECT COUNT(*)FROM CERTIFICATE WHERE LOCATION = 'Львів'),
          (SELECT COUNT(*)FROM CERTIFICATE WHERE LOCATION = 'Кременець')
    FROM CERTIFICATE;

SELECT * From COUNT_CERTIFICATE_BY_LOCATION;

DROP VIEW COUNT_CERTIFICATE_BY_LOCATION;

--2.3

CREATE VIEW COUNT_ISSUE_DATE(ISSUE_DATE,DATE_COUNT)
as SELECT C.ISSUE_DATE,COUNT(C.ISSUE_DATE)
   FROM CERTIFICATE C
   GROUP BY C.ISSUE_DATE;

SELECT * FROM COUNT_ISSUE_DATE WHERE DATE_COUNT > 4;

DROP VIEW COUNT_ISSUE_DATE;
