CREATE TABLE CERTIFICATE(
  Num NUMBER NOT NULL,
  Name VARCHAR2(20 CHAR) NOT NULL,
  Issue_Date DATE NOT NULL,
  Addressee VARCHAR2(30 CHAR) NOT NULL,
  Location VARCHAR2(30 CHAR),
  SNF VARCHAR2(35 CHAR) NOT NULL,
  Text LONG NOT NULL,
  Appointment VARCHAR2(50 CHAR),
  Lable BLOB,
  Stamp BLOB
);

CREATE TABLE SPESIAL_FORM(
  Num NUMBER,
  SNF VARCHAR2(35 CHAR),
  Phone VARCHAR2(10 CHAR),
  Issue_Date DATE
);

CREATE TABLE PERSON(
  SNF VARCHAR2(35 CHAR)
);

CREATE TABLE ADMINISTRATION(
  Lable BLOB NOT NULL
);