CREATE TABLE CERTIFICATE(
  CERTIFICATEPK NUMBER PRIMARY KEY,
  Name VARCHAR2(20 CHAR) NOT NULL,
  Issue_Date DATE NOT NULL,
  Addressee VARCHAR2(30 CHAR),
  Location VARCHAR2(30 CHAR),
  PERSONFK NUMBER NOT NULL,
  Text LONG NOT NULL
);

CREATE TABLE SPESIAL_FORM(
  SPESIAL_FORMPK NUMBER PRIMARY KEY,
  PERSONFK NUMBER NOT NULL
);

CREATE TABLE MY_FORM(
   SPESIAL_FORMFK NUMBER NOT NULL,
   CERTIFICATEFK NUMBER NOT NULL
);

CREATE TABLE PERSON(
  PERSONPK NUMBER PRIMARY KEY,
  NAME VARCHAR2(35 CHAR) NOT NULL,
  Phone VARCHAR2(10 CHAR)
);


DROP TABLE CERTIFICATE;
DROP TABLE SPESIAL_FORM;
DROP TABLE PERSON;
DROP TABLE MY_FORM;