ALTER TABLE SERTIFICATE
ADD CONSTRAINT Num_PK
PRIMARY KEY (Num);

ALTER TABLE SERTIFICATE
ADD CONSTRAINT Num_UNIQUE
UNIQUE (Num);

ALTER TABLE PERSON
ADD CONSTRAINT SNF_PK
PRIMARY KEY (SNF);

ALTER TABLE PERSON
ADD CONSTRAINT SNF_UNIQUE
UNIQUE (SNF);

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT Phone_PK
PRIMARY KEY (Phone);


ALTER TABLE PERSON
ADD CONSTRAINT SNF_CHECK_PERSON
CHECK(REGEXP_LIKE(SNF,'[ј-я]{1}[а-€]* [ј-я]{1}[а-€]* [ј-я]{1}[а-€]*'));


ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT Num_FK_FORM
FOREIGN KEY (Num)
REFERENCES CERTIFICATE (Num)
ON DELETE CASCADE;

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT Num_CHECK_FORM
CHECK(REGEXP_LIKE(Num,'[0-9]{10}'));

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT SNF_FK_FORM 
FOREIGN KEY (SNF)
REFERENCES PERSON (SNF)
ON DELETE SET NULL;

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT SNF_CHECK_FORM
CHECK(REGEXP_LIKE(SNF,'[ј-я]{1}[а-€]* [ј-я]{1}[а-€]* [ј-я]{1}[а-€]*'));

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT Phone_CHECK_FORM
CHECK(REGEXP_LIKE(Phone,'[0-9]{10}'));

ALTER TABLE CERTIFICATE
ADD CONSTRAINT Issue_Date_UNIQUE
UNIQUE (Issue_Date);

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT Issue_Date_FK_FORM
FOREIGN KEY (Issue_Date)
REFERENCES CERTIFICATE (Issue_Date);

ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT Num_UNIQUE_FORM
UNIQUE (Num);


ALTER TABLE ADMINISTRATION
MODIFY(Lable DEFAULT NULL);


ALTER TABLE CERTIFICATE
ADD CONSTRAINT Name_CHECK
CHECK(NAME IN ('–ћѕ','ƒѕЌѕ','ƒѕЌ','¬оЇнний б≥лет','ƒѕ«ѕ'));

ALTER TABLE CERTIFICATE
ADD CONSTRAINT Location_CHECK
CHECK(Location IN (' ињв',' ременець','’арк≥в','Ћьв≥в','—апан≥в'));

ALTER TABLE CERTIFICATE
ADD CONSTRAINT SNF_FK_SERTIFICATE
FOREIGN KEY (SNF)
REFERENCES PERSON (SNF);

ALTER  TABLE CERTIFICATE
ADD CONSTRAINT Name_Appointment_UNIQUE
UNIQUE(Name, Appointment);