CREATE TABLE LECTURE(
  TchFK NUMBER,
  GrpFK Number,
  SbjFK NUMBER,
  RomFK NUMBER,
  Type VARCHAR2(15 CHAR),
  Day CHAR(3),
  Week NUMBER(1),
  Lesson NUMBER(1)
);

CREATE TABLE ROOM(
  RomPK Number,
  Num NUMBER(4),
  Seats NUMBER(3),
  Floor NUMBER(2),
  Building CHAR(5 CHAR)
);

CREATE TABLE SUBJECT(
  SbjPK NUMBER,
  Name VARCHAR2(50 CHAR)
);

CREATE TABLE SGROUP(
  GrpPK NUMBER,
  DepFK NUMBER,
  Course NUMBER(1),
  Num NUMBER(3),
  Quantity NUMBER(2),
  Curator NUMBER,
  Rating NUMBER
);

CREATE TABLE TEACHER(
  TchPK NUMBER,
  DepFK NUMBER,
  Name VARCHAR2(50 CHAR),
  Post VARCHAR2(15 CHAR),
  Tel CHAR(7 CHAR),
  Hiredate DATE,
  Salary NUMBER(6,2),
  Commission NUMBER(6,2),
  ChiefFK NUMBER
);

CREATE TABLE DEPARTMENT(
  DepPK NUMBER,
  FacFK NUMBER,
  Name VARCHAR2(50 CHAR),
  HeadFK NUMBER,
  Building Char(3 CHAR),
  Fund NUMBER(8,2)
);

CREATE TABLE FACULTY(
  FacPK NUMBER,
  Name VARCHAR2(50 CHAR),
  DeanFK NUMBER,
  Building CHAR(2 CHAR),
  Fund NUMBER(9,2)
);

DROP TABLE FACULTY;
DROP TABLE DEPARTMENT;
DROP TABLE TEACHER;
DROP TABLE SGROUP;
DROP TABLE SUBJECT;
DROP TABLE ROOM;
DROP TABLE LECTURE;