CREATE TABLE HUMAN(
  HumanPK NUMBER PRIMARY KEY,
  UnitFK NUMBER,
  Name VARCHAR2(25 CHAR) NOT NULL,
  Sername VARCHAR2(25 CHAR) NOT NULL,
  ProfFK NUMBER,
  Birth DATE NOT NULL,
  Sex CHAR(1) CHECK(Sex IN ('W','M')) NOT NULL
);

CREATE TABLE PROFESSION(
  ProfPK NUMBER PRIMARY KEY,
  Name VARCHAR2(25 CHAR) NOT NULL,
  Salary NUMBER
);

CREATE TABLE CERTIFICATION_TYPE(
  Certific_typePK NUMBER PRIMARY KEY,
  Name VARCHAR2(25 CHAR) NOT NULL
);

CREATE TABLE CERTIFICATION(
  HumanFK NUMBER REFERENCES CERTIFICATION_TYPE (Certific_typePK) ON DELETE CASCADE,
  Certific_typeFK NUMBER NOT NULL,
  Exam_date DATE,
  STATE VARCHAR2(5 char) CHECK(STATE in ('TRUE', 'FALSE'))
);

CREATE TABLE DOCUMENTS(
  HumanFK NUMBER REFERENCES Human (HumanPK) ON DELETE CASCADE NOT NULL,
  Pasporid VARCHAR2(9 char) CHECK(REGEXP_LIKE(Pasporid , '[0-9]{9}')) NOT NULL,
  Hiredate DATE,
  Identification_code VARCHAR2(10 CHAR) CHECK(REGEXP_LIKE(Identification_code,'[0-9]{9}')) NOT NULL,
  Work_book VARCHAR2(6 CHAR) CHECK(REGEXP_LIKE(Work_book, '[0-9]{6}'))
);

CREATE TABLE UNIT(
  UnitPK NUMBER PRIMARY KEY,
  Name VARCHAR2(25 CHAR) NOT NULL,
  DepFK NUMBER,
  Premium NUMBER,
  LEADER NUMBER
);

CREATE TABLE DEPARTMENT_HUMAN(
  DepPK NUMBER PRIMARY KEY,
  Name VARCHAR2(25 CHAR) NOT NULL,
  FUND NUMBER,
  LEADER NUMBER
);

DROP TABLE HUMAN;
DROP TABLE PROFESSION;
DROP TABLE CERTIFICATION;
DROP TABLE CERTIFICATION_TYPE;
DROP TABLE DOCUMENTS;
DROP TABLE UNIT;
DROP TABLE DEPARTMENT_HUMAN;