--Lab 2.3
--Завдання 1(- операція об'єднання ( (UNION, UNION ALL та вираз
--             об'єднання через логічну зв'язку OR);
--           - операція об'єднання з будь-якими операторами але з
--             підзапитами;
--           - операції об'єднання з групуванням (додаткові умови за
--             бажанням))

SELECT NAME FROM FACULTY
UNION ALL
SELECT NAME FROM DEPARTMENT D WHERE D.DEPPK=1 or D.DEPPK=2 or D.DEPPK=4; 

SELECT NAME 
FROM TEACHER T 
WHERE T.HIREDATE BETWEEN TO_DATE('01.01.2000','DD.MM.YYYY') and TO_DATE('31.12.2000','DD.MM.YYYY')
UNION
SELECT NAME 
FROM TEACHER T 
WHERE T.HIREDATE BETWEEN TO_DATE('01.01.1990','DD.MM.YYYY') and TO_DATE('31.12.1998','DD.MM.YYYY');

SELECT NAME 
FROM TEACHER T 
WHERE T.HIREDATE BETWEEN TO_DATE('01.01.2000','DD.MM.YYYY') and TO_DATE('31.12.2000','DD.MM.YYYY') or
      T.HIREDATE BETWEEN TO_DATE('01.01.1990','DD.MM.YYYY') and TO_DATE('31.12.1998','DD.MM.YYYY');

SELECT NUM, G.RATING, Round(K, 2)
FROM SGROUP G,(SELECT AVG(RATING) K from SGROUP)
WHERE G.RATING > K
UNION ALL
SELECT NUM, G.RATING, NULL
FROM SGROUP G
ORDER BY 3 DESC, 2 DESC;

SELECT G.NUM, COUNT(distinct L.TYPE)
FROM LECTURE L INNER JOIN SGROUP G on L.GRPFK = G.GRPPK
GROUP BY G.NUM;

--Завдання 2(- операція перетину з під запитами (INTERSECT, вираження
--             INTERSECT через послідовність операторів IN, що
--             з'єднуються логічною зв'язкою AND).)

SELECT NUM, G.RATING
FROM SGROUP G,(SELECT AVG(RATING) K from SGROUP)
WHERE G.RATING > K-20
INTERSECT
SELECT NUM, G.RATING
FROM SGROUP G,(SELECT AVG(RATING) K from SGROUP)
WHERE G.RATING < K+20
ORDER BY 2 DESC;

SELECT NUM, G.RATING
FROM SGROUP G,(SELECT AVG(RATING) K from SGROUP)
WHERE G.RATING > K-20 and G.RATING < K+20
ORDER BY 2 DESC;

--Завдання 3(- операція різниці (MINUS, вираження MINUS через NOT IN).)

SELECT NUM, G.RATING
FROM SGROUP G
MINUS
SELECT NUM, G.RATING
FROM SGROUP G,(SELECT AVG(RATING) K from SGROUP)
WHERE G.RATING < K
ORDER BY 2 DESC;

SELECT NUM, G.RATING
FROM SGROUP G,(SELECT AVG(RATING) K from SGROUP)
WHERE NOT G.RATING < K
ORDER BY 2 DESC;
