ALTER TABLE PERSON
ADD CONSTRAINT Phone_UNIQUE
UNIQUE (Phone);

ALTER TABLE PERSON
ADD CONSTRAINT PHONE_CHECK
CHECK(REGEXP_LIKE(PHONE,'[0-9]{10}'));

ALTER TABLE PERSON
ADD CONSTRAINT NAME_CHECK_PERSON
CHECK(REGEXP_LIKE(NAME,'[А-Я]{1}[а-я]* [А-Я]{1}[а-я]* [А-Я]{1}[а-я]*'));


ALTER TABLE SPESIAL_FORM
ADD CONSTRAINT PERSON_FK_FORM
FOREIGN KEY (PERSONFK)
REFERENCES PERSON (PERSONPK)
ON DELETE CASCADE;


ALTER TABLE CERTIFICATE
ADD CONSTRAINT Name_CHECK
CHECK(NAME IN ('РМП','ДПНП','ДПН','Воєнний білет','ДПЗП'));

ALTER TABLE CERTIFICATE
ADD CONSTRAINT Location_CHECK
CHECK(Location IN ('Київ','Кременець','Харків','Львів','Сапанів'));

ALTER TABLE CERTIFICATE
ADD CONSTRAINT PERSON_FK_CERTIFICATE
FOREIGN KEY (PERSONFK)
REFERENCES PERSON (PERSONPK);


ALTER TABLE MY_FORM
ADD CONSTRAINT SPESIAL_FORM_FK_MY_FORM
FOREIGN KEY (SPESIAL_FORMFK)
REFERENCES SPESIAL_FORM (SPESIAL_FORMPK);

ALTER TABLE MY_FORM
ADD CONSTRAINT CERTIFICATE_FK_MY_FORM
FOREIGN KEY (CERTIFICATEFK)
REFERENCES CERTIFICATE (CERTIFICATEPK);
